/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "tertiary": "#bbc7dc",
        "secondary": "#bfc6dc",
        "tertiary-container": "#8b97ab",
        "on-background": "#e1e3e4",
        "on-surface": "#e1e3e4",
        "on-primary-container": "#5b1604",
        "on-secondary-container": "#adb5ca",
        "surface-container-low": "#191c1d",
        "surface-container": "#1d2021",
        "tertiary-fixed-dim": "#bbc7dc",
        "on-primary": "#5d1805",
        "on-tertiary": "#253141",
        "inverse-on-surface": "#2e3132",
        "background": "#111415",
        "secondary-fixed-dim": "#bfc6dc",
        "surface-dim": "#111415",
        "outline": "#a38b86",
        "secondary-fixed": "#dbe2f9",
        "on-secondary": "#293041",
        "surface-container-lowest": "#0c0f10",
        "on-tertiary-container": "#242f40",
        "primary-fixed-dim": "#ffb4a1",
        "error-container": "#93000a",
        "surface-variant": "#323536",
        "inverse-primary": "#9a442d",
        "on-primary-fixed-variant": "#7c2e19",
        "surface-container-high": "#282a2b",
        "surface": "#111415",
        "tertiary-fixed": "#d7e3f9",
        "inverse-surface": "#e1e3e4",
        "on-tertiary-fixed": "#101c2c",
        "on-tertiary-fixed-variant": "#3c4859",
        "on-error": "#690005",
        "on-surface-variant": "#dbc1ba",
        "surface-tint": "#ffb4a1",
        "on-secondary-fixed-variant": "#3f4759",
        "primary-container": "#e07a5f",
        "outline-variant": "#55423e",
        "secondary-container": "#3f4759",
        "primary": "#ffb4a1",
        "surface-container-highest": "#323536",
        "surface-bright": "#373a3b",
        "on-primary-fixed": "#3c0800",
        "on-secondary-fixed": "#141b2c",
        "primary-fixed": "#ffdbd2",
        "brand-accent": "#e07a5f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "display-lg": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-md": ["Manrope"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg-mobile": ["Manrope"]
      },
      fontSize: {
        "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-md": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
