import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { Link } from 'react-router-dom';

export default function DocumentsPage() {
  const { authFetch } = useAuth();
  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchDocs = async () => {
      try {
        const res = await authFetch('/documents');
        if (!res.ok) throw new Error('Failed to fetch documents');
        const data = await res.json();
        setDocuments(data);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchDocs();
  }, [authFetch]);

  return (
    <div className="flex-1 px-margin-mobile md:px-margin-desktop max-w-container-max w-full mx-auto py-8 animate-page-enter">
      <div className="mb-10">
        <h2 className="font-display-md text-display-md text-on-surface">Documents</h2>
        <p className="font-body-lg text-body-lg text-on-surface-variant mt-2">All generated documents from your cases in one place.</p>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3].map(i => (
            <div key={i} className="glass-card rounded-2xl p-6 h-48 animate-pulse"></div>
          ))}
        </div>
      ) : error ? (
        <div className="glass-panel rounded-2xl p-12 flex flex-col items-center justify-center text-center">
          <span className="material-symbols-outlined text-error text-4xl mb-4">error</span>
          <p className="text-on-surface">{error}</p>
        </div>
      ) : documents.length === 0 ? (
        <div className="glass-panel rounded-2xl p-12 flex flex-col items-center justify-center gap-6 min-h-[400px] text-center">
          <div className="w-20 h-20 rounded-full bg-surface-container-high flex items-center justify-center">
            <span className="material-symbols-outlined text-on-surface-variant text-4xl">description</span>
          </div>
          <div>
            <h3 className="font-headline-lg text-headline-lg text-on-surface mb-2">No documents yet</h3>
            <p className="font-body-md text-body-md text-on-surface-variant max-w-md">
              Documents generated by the AI (like demand letters or RTI applications) during your case journey will automatically appear here.
            </p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {documents.map(doc => (
            <div key={doc.id} className="glass-card rounded-2xl p-6 flex flex-col hover:border-primary/30 transition-colors group relative overflow-hidden">
              <div className="absolute top-0 right-0 w-24 h-24 bg-primary/10 rounded-bl-[100px] -z-10 group-hover:bg-primary/20 transition-colors"></div>
              <div className="flex items-start justify-between mb-4">
                <div className="w-12 h-12 rounded-xl bg-primary/15 flex items-center justify-center text-primary">
                  <span className="material-symbols-outlined">description</span>
                </div>
                <div className="text-[10px] text-on-surface-variant bg-surface-container px-2 py-1 rounded">
                  {new Date(doc.created_at).toLocaleDateString()}
                </div>
              </div>
              <h3 className="font-headline-sm text-on-surface font-medium truncate mb-1" title={doc.document_type}>
                {doc.document_type}
              </h3>
              <div className="flex items-center gap-1.5 text-xs text-on-surface-variant mb-6 truncate">
                <span className="material-symbols-outlined text-[14px]">folder</span>
                <span className="truncate">{doc.case_title}</span>
              </div>
              <div className="mt-auto flex gap-2">
                <a 
                  href={doc.pdf_base64 ? `data:application/pdf;base64,${doc.pdf_base64}` : doc.pdf_url}
                  download={doc.document_type ? `${doc.document_type.replace(/[^a-zA-Z0-9]/g, '_')}.pdf` : 'Document.pdf'}
                  target={doc.pdf_base64 ? undefined : "_blank"}
                  rel="noopener noreferrer"
                  className="flex-1 py-2 rounded-lg bg-primary text-on-primary-fixed text-center font-label-sm text-xs hover:opacity-90 transition-opacity flex justify-center items-center gap-1.5"
                >
                  <span className="material-symbols-outlined text-[14px]">download</span> Download PDF
                </a>
                <Link
                  to={`/dashboard/case/${doc.case_id}`}
                  className="px-3 py-2 rounded-lg bg-surface-container hover:bg-surface-container-high border border-white/5 text-on-surface font-label-sm text-xs transition-colors flex items-center justify-center"
                  title="View Case"
                >
                  <span className="material-symbols-outlined text-[16px]">arrow_forward</span>
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
