export const staticContent = {
  privacy: {
    title: "Privacy Policy",
    sections: [
      {
        heading: "1. Information We Collect",
        paragraphs: [
          "At Adhikaar, safeguarding your privacy is a foundational principle. We collect the absolute minimum information necessary to provide our AI-driven legal and civic guidance. This includes your email address, name, and securely hashed passwords when you create an account.",
          "During the case intake process, we collect the narrative details of your situation and any documentary evidence (such as PDFs, receipts, or images) that you choose to upload. We do not track your browsing activity across other websites or use invasive tracking cookies."
        ]
      },
      {
        heading: "2. How We Use Your Data",
        paragraphs: [
          "Your data is used exclusively to operate, maintain, and improve the Adhikaar platform. The specific details of your cases and uploaded evidence are processed by our specialized Large Language Models strictly for the purpose of generating legal guidance, structuring demand letters, or drafting RTI applications tailored to your exact situation.",
          "We firmly believe that your legal matters are your business alone. Adhikaar does not sell, rent, or lease your personal data to third parties, marketers, or data brokers under any circumstances."
        ]
      },
      {
        heading: "3. Data Security & Isolation",
        paragraphs: [
          "All sensitive documents and evidence you upload are securely transmitted and stored on encrypted cloud servers (AWS/Cloudinary). Our database employs strict Row Level Security (RLS) policies, ensuring that your cases, action plans, and AI chat logs are cryptographically isolated and completely inaccessible to any other user on the platform.",
          "If you wish to permanently delete your account and all associated data from our servers, you may request account deletion at any time by contacting our support team."
        ]
      }
    ]
  },
  terms: {
    title: "Terms of Service",
    sections: [
      {
        heading: "1. Acceptance of Terms",
        paragraphs: [
          "By accessing, browsing, or using the Adhikaar platform, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree to these terms, you must immediately cease using the platform."
        ]
      },
      {
        heading: "2. Scope of Service",
        paragraphs: [
          "Adhikaar provides an AI-powered assistant designed to democratize access to Indian civic and legal knowledge. The platform processes user queries against a curated database of public domain legal texts to provide automated, plain-language explanations and draft documents.",
          "You agree to use this service exclusively for lawful purposes. You shall not use Adhikaar to generate fraudulent claims, harass third parties, or engage in any activity that violates the laws of India."
        ]
      },
      {
        heading: "3. User Responsibilities",
        paragraphs: [
          "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate and complete information during the intake process, as the quality of the AI-generated guidance directly depends on the accuracy of the facts you provide."
        ]
      }
    ]
  },
  disclaimer: {
    title: "Legal Disclaimer",
    sections: [
      {
        heading: "1. Not Legal Advice",
        paragraphs: [
          "The information, documents, and action plans generated by Adhikaar are provided for educational and informational purposes only. Adhikaar is an AI-powered platform and software tool, not a law firm. The use of this platform does not constitute formal legal advice, nor does it establish an attorney-client relationship between you and Adhikaar or its creators."
        ]
      },
      {
        heading: "2. AI Limitations & Verification",
        paragraphs: [
          "While we strive to ensure our AI is strictly grounded in official Indian legislation (such as the Consumer Protection Act, RTI Act, and Model Tenancy Act), laws frequently change, and AI systems can occasionally misinterpret nuances or hallucinate details.",
          "You must independently verify any legal citations provided by the platform before using them in a formal legal proceeding. Always consult a qualified, registered legal professional for serious legal matters, litigation, or complex disputes."
        ]
      },
      {
        heading: "3. Limitation of Liability",
        paragraphs: [
          "Under no circumstances shall Adhikaar, its developers, or its affiliates be held liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the platform, or from any actions taken based on the AI-generated guidance."
        ]
      }
    ]
  },
  contact: {
    title: "Contact Us",
    sections: [
      {
        heading: "Get in Touch",
        paragraphs: [
          "Whether you have technical questions, feedback on the AI's responses, or need assistance with your account, our team is here to help you navigate your civic rights."
        ],
        list: [
          "Email Support: support@adhikaar.org",
          "Legal Queries: legal@adhikaar.org",
          "Toll-Free Helpline: +91 1800-123-4567 (Mon-Fri, 9 AM - 6 PM IST)"
        ]
      },
      {
        heading: "Headquarters",
        paragraphs: [
          "Adhikaar Legal Tech Initiative",
          "123 Civic Center, Innovation Block A",
          "New Delhi, India 110001"
        ]
      }
    ]
  },
  press: {
    title: "Press Kit",
    sections: [
      {
        heading: "About Adhikaar",
        paragraphs: [
          "Adhikaar is a non-profit AI initiative aimed at democratizing legal and civic knowledge for the 1.4 billion citizens of India. By leveraging advanced Large Language Models and Retrieval-Augmented Generation (RAG) technology, we transform complex, jargon-heavy Indian laws into accessible, actionable guidance for everyday people.",
          "Our mission is to ensure that a lack of financial resources or legal literacy never prevents a citizen from exercising their fundamental rights, claiming a refund, or holding public authorities accountable."
        ]
      },
      {
        heading: "Media Assets & Inquiries",
        paragraphs: [
          "Members of the press can request access to our high-resolution logos, product screenshots, brand guidelines, and founder interviews.",
          "Please direct all media and press inquiries to press@adhikaar.org. Our media team typically responds within 24 hours."
        ]
      }
    ]
  },
  howItWorks: {
    title: "How It Works",
    sections: [
      {
        heading: "Step 1: Explain Your Situation",
        paragraphs: [
          "Start your journey using our intelligent Intake Wizard. You can type out your problem in plain language or use our Voice Dictation feature. Whether you are dealing with a landlord dispute, a defective product, or a delayed passport, simply tell us what happened.",
          "You can also seamlessly upload up to 5 pieces of evidence (like receipts, rental agreements, or photos of defective items) directly into our secure vault."
        ]
      },
      {
        heading: "Step 2: AI Analysis & Grounding",
        paragraphs: [
          "Our proprietary 'Legal Brain' goes to work immediately. It processes your narrative and searches through a massive database of verified Indian Laws—including the RTI Act, Consumer Protection Act, and Tenancy Laws.",
          "It cross-references your specific facts against the law to find the exact sections and clauses that protect you, completely eliminating guesswork and AI hallucinations."
        ]
      },
      {
        heading: "Step 3: Action Plan & Document Generation",
        paragraphs: [
          "Within seconds, you receive a clear, step-by-step Action Plan explaining exactly what you should do next in plain, 8th-grade English.",
          "If your situation requires a formal response, the AI will instantly generate a ready-to-use Legal Notice, Demand Letter, or RTI Application. These documents are professionally formatted, precisely cited, and tailored specifically to your exact situation, ready to be downloaded or printed."
        ]
      }
    ]
  }
};
